### PR TITLE
Changed Header of Most Recent Change

### PR DESCRIPTION
**Pull request by shli3**
### What are you trying to accomplish?
Less redundancy in names, better organization

### How are you accomplishing it?
Simple name change

### Is there anything reviewers should know?
Brandon is awesome :) (dkm)

- [x] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Comment by EricPickup** [comment]
I don't see what's wrong with `Resources`, personally I prefer it since most of those links aren't tools.

cc @Scetch

**Comment by shli3** [comment]
I was just thinking the header should be a different name only because the dropdown on the very top bar is also called resources. 

I think the header on the resources page should be named something different as it may imply that everything else on that page is not considered a resource, even though it's on the resources page.

**Comment by Scetch** [comment]
I didn't see a notification for this. Whoops.

I agree that it's confusing, but I also agree with @EricPickup in that they aren't all tools. Perhaps the header dropdown itself could use a rename? Or we can remove the dropdown all together and have a Facebook icon, tutoring schedule & student guide on the nav bar, and move `Contributing` to a GitHub icon?

**Comment by shli3** [comment]
Either solution would work, I agree with yours though

**Comment by EricPickup** [comment]
I think "Useful Links" would be a better option @shli3

**Pull request merged**
