### PR TITLE
LGTM: Added bookmarks for subheadings in student guide

### PR DESCRIPTION
**Pull request by amanpatel123**
### What are you trying to accomplish?
- This is an attempt to address issue #105. Basically, I am trying to add a bookmark to subsection/subheading.

### How are you accomplishing it?
-  Just using basic markups

### Is there anything reviewers should know?
- Yes, The link for the following does not work since they all have some unique characters in them. 
   * Bird (very easy) courses
   * Frequently Asked Questions (FAQ)
   *  Working in the U.S.A.
- Do you have any idea on how to fix this?

- [x] Is it safe to rollback this change if anything goes wrong?
absolutely!

### CODE REVIEW

**Comment by EricPickup** [comment]
@amanpatel123 this is awesome! This will be so useful, much needed.

To fix the broken ones you can just change it to remove the characters:
- Easy courses
- Frequently Asked Questions
- Working in the USA

Also make sure to add your name to the list of contributors!

**Comment by amanpatel123** [comment]
@EricPickup thank you so much for such quick response. I will change it right now

**Comment by EricPickup** [comment]
@amanpatel123 is this still a WIP? Otherwise it LGTM

**Comment by amanpatel123** [comment]
Oh missed that, It is LGTM!

**Comment by amanpatel123** [comment]
Thanks!

**Pull request merged**
